### ISSUE TITLE
One-time ignoring package while upgrading

### ISSUE THREAD

**Issue by GoldsteinE** [vn971/rua#107]
Subj. It would be cool if `rua upgrade` has option to select which packages to ignore in this run.

**Comment by vn971** [comment]
@GoldsteinE sounds like a nice feature. Would you be willing to try and write a PR?

**Comment by vn971** [comment]
BTW, note that you can also permanently exclude packages form upgrading by using `IgnorePkg` section of `/etc/pacman.conf` (same as with non-AUR packages and pacman).

**Comment by mqus** [comment]
It's now (in the next release) possible to ignore e.g. packages `a` and `b` by using 
```
rua upgrade --ignore a,b
```
or
```
rua upgrade --ignore=a,b
```
.
