### ISSUE TITLE
Message on successful build could be more helpful

### ISSUE THREAD

**Issue by gnzlbg** [vn971/rua#108]
Hi @vn971 , I really love rua, it is the best tool I've used so far for managing the AUR packages. 

Sometimes, the `rua install` fails (e.g. because of `chown`, see other issues), and I end up building the packages using `rua builddir` instead. After doing that, `rua` prints:

> Package built and checked in: /home/gonzalob/.cache/rua/build/<pckg-name>
> If you want to install the built artifacts, do it manually.

It would be nice if it could directly print the pacman command to do that, so that I just needs to copy paste it into the terminal. This isn't very annoying, but it is probably something that could be done much better by putting relatively a low amount of work into it.

Keep up the good work you are doing here!

**Comment by vn971** [comment]
Hi @gnzlbg, thanks for the feedback, really glad to have it!

Totally agree with the issue. Would you want to implement it? If not, I might take over and implement it, but if you'd like to give it a try yourself, you're most welcome.
