### ISSUE TITLE
Reformat code?

### ISSUE THREAD

**Issue by senden9** [vn971/rua#11]
Hi!

I thought about to reformat this codebase automatically with `cargo fmt`. But this would lead to many changes just for style. See https://github.com/senden9/rua/compare/c100c91960427857d555107a2b9a5cc573a7e725...senden9:6d6bbacf846e77abcf401c581eb5b4eb05e43cb2 for a result. If you want I open an PR for that changes. If not we let the code base at it is at the moment.

**Comment by vn971** [comment]
Thanks for raising the issue!

It started as a personal project for myself, I didn't know if people would enjoy the alternative. So I've picked some personal coding habits.
At this point, however, it make sense to make the codebase convenient for possible future contributors, so making code `cargo fmt` compatible would definitely be good.

I'll try to address the pull request first to avoid conflicts: https://github.com/vn971/rua/pull/10  and then do the `cargo fmt` change.

**Comment by vn971** [comment]
Apparently the branch was on top of the other PR already. There's one issue I see though: the source code is not formatted fully https://github.com/senden9/rua/compare/c100c91960427857d555107a2b9a5cc573a7e725...senden9:6d6bbacf846e77abcf401c581eb5b4eb05e43cb2#diff-53a8cadd501570cca53504b48b23ccfe
you can see both spaces and tabs here. That's something we definitely want to avoid. Looking into it now.

**Comment by vn971** [comment]
done! I've just manually replaced the remaining tabs, so it's only 4 spaces for indentation now.

**Comment by senden9** [comment]
Great. Have you seen that you can adapt the style if you want with a config file in the project root? https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

I do not recommend this but then you can have also your own style _and_ some tool to enforce it. For my the style dosnt matter relay as long as is consistent over the project.

**Comment by vn971** [comment]
I've currently added both (clippy and rustfmt) in CI, but I'm OK with exclusions if valid code would receive false warnings.
