### ISSUE TITLE
`--ignore`  is a required argument to `upgrade`

### ISSUE THREAD

**Issue by olantwin** [vn971/rua#123]
With the most recent release, `rua upgrade` fails:
```
error: The following required arguments were not provided:
    --ignore <ignored>
```

It seems like `--ignore` was accidentally added as a required argument rather than as an optional argument in #122 .

I'll have a look whether I can fix this, but I'm unfortunately not particularly familiar with rust and the way the arguments are parsed.

**Comment by vn971** [comment]
Thanks for the bug report, I understood what's happening, will fix now.

**Comment by vn971** [comment]
Fixed that, making a release now. Thanks again for the bug report!

**Comment by olantwin** [comment]
Thanks for the quick fix!

Also learnt a thing or two while trying to fix it myself (and comparing my solution to your better one ;) )

**Comment by vn971** [comment]
I think both solutions are good actually - just ended up committing mine because I already had a release in progress (and I like flat_map-s:). Cheers.
