### ISSUE TITLE
Bug: rua can't detect a library `hunspell-en_US`

### ISSUE THREAD

**Issue by VitalyAnkh** [vn971/rua#127]
When I let `rua` install a package, it said:
![image](https://user-images.githubusercontent.com/24508452/83267724-3831c000-a1f7-11ea-81fa-aadc0b8c79c7.png)
But `hunspell-en_US` has been already installed. Is the difference between `hunspell-en_US` and `hunspell-en_us` that caused this problem?
![image](https://user-images.githubusercontent.com/24508452/83268081-b1311780-a1f7-11ea-96c2-eab858b3e6aa.png)

**Comment by vn971** [comment]
Indeed it seems so.. Lemme look around in AUR and this package.

**Comment by vn971** [comment]
Thanks for reporting the issue! It's a bug apparently, a mishandling of alphanumeric package names (I assumed they are lowercase, but the `man PKGBUILD` says "alphanumeric"). I've made a fix, releasing a new version now.

**Comment by vn971** [comment]
Thanks! :muscle:
