### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by senden9** [vn971/rua#13]
Display the user hits for the `search` subcommand. For the printing we can use something like [prettytable](https://github.com/phsym/prettytable-rs) plus the AUR search api.

At the moment the user gets only a link that needs to be opend in some browser, go back to the terminal & type the install command. This is not the most ergonomic workflow.

**Comment by vn971** [comment]
I'd also like to note the existence of "aur" crate: https://github.com/rusty-crates/aur.rs ,which wraps the JSON API into Rust. I think using this crate is a good path for RUA to go, eventually.
// I've planned to do it, but just moved to a new city and new country recently, didn't have time to return to it properly yet.

That is definitely doable.

**Comment by senden9** [comment]
Thank for the tip. I am just a Arch Linux user and rust programmer that want a good aur helper. So i will add pul lrequest from time to time if something bugs me.

**Comment by vn971** [comment]
@senden9 sure! This is exactly my approach, and my description as well so far.:)

// Well, plus namespace security isolation, but this part was first and it's finished now.

**Comment by vn971** [comment]
We implemented (and refined) "search" functionality, it's available as `rua search target` :)
