### ISSUE TITLE
Rua fails to build rust package

### ISSUE THREAD

**Issue by nilehmann** [vn971/rua#130]
I'm trying to install [starship](https://aur.archlinux.org/packages/starship/) and I get the following error.

```
==> Starting build()...
error: no default toolchain configured
```
I'm using rustup to manage my rust toolchains and the package builds without any problems if I run `makepkg` manually.

**Comment by nilehmann** [comment]
I did a better reading of the README and realized this is due to the safe safe environment and one just needs to add a new mount point with the rust up folder. Sorry for the noise.

**Comment by vn971** [comment]
@nilehmann hi, yeah, you need to specify the toolchain for Rust OR at least once download any Rust toolchain. (Was busy, didn't have time to answer before).

**Comment by refaelsh** [comment]
I have the same issue exactly.
@nilehmann What do you mean a mount folder with `rustup`? Can you please help me?

**Comment by refaelsh** [comment]
@nilehmann I specified toolchain and at least once downloaded Rust toolchain.
The problem still occurs.

**Comment by nilehmann** [comment]
@refaelsh take a look at this section https://github.com/vn971/rua#safety. Rua runs in an isolated environment and by default, it doesn't have access to the entire filesystem. Rustup stores your toolchains in your home directory so you need to give explicit access to it. You can do that by adding a file in `~/.config/rua/wrap_args.d/`. Mine looks like this:

```bash
$ ls ~/.config/rua/wrap_args.d
wrap_args_bind.sh

$ cat ~/.config/rua/wrap_args.d/wrap_args_bind.sh
wrap_args+=(--bind-try ~/.cargo ~/.cargo)
wrap_args+=(--bind-try ~/.rustup ~/.rustup)
```
