### ISSUE TITLE
Can I allow access to things outside the jail?

### ISSUE THREAD

**Issue by Amanita-muscaria** [vn971/rua#131]
I recently installed linux-clear using my own module configuration. After trying for a while to figure out why the build wasn't able to find the requisite file despite it being in the correct location, I realized it was due to the build being in jail and the file being out of the jail. Is there a way to tell rua that it's cool to allow access to that file?

**Comment by vn971** [comment]
Hi @Amanita-muscaria , this is what "wrap_args" are for. It's the arguments passed directly to `bubblewrap`, the security jail that does filesystem isolation (among other). See example in `~/.config/rua/.system/wrap_args.sh.example`

Feel free to ask if you have any questions.

**Comment by Amanita-muscaria** [comment]
Oh, perfect. Thank you!
