### ISSUE TITLE
Improper quoting of PKGBUILD.static

### ISSUE THREAD

**Issue by ldr709** [vn971/rua#15]
[static_pkgbuild](https://github.com/vn971/rua/blob/master/src/srcinfo.rs#L83`) doesn't properly quote strings. This makes packages with apostrophes in their descriptions, such as `ruby-stringex`, fail to build.

    /home/aur/.cache/rua/ruby-stringex/build/PKGBUILD.static: line 13: unexpected EOF while looking for matching `''
    /home/aur/.cache/rua/ruby-stringex/build/PKGBUILD.static: line 14: syntax error: unexpected end of file
    ==> ERROR: Failed to source /home/aur/.cache/rua/ruby-stringex/build/PKGBUILD.static
(followed by a panic)

**Comment by vn971** [comment]
Apparently this line fails to work the way I expected it to work: https://github.com/vn971/rua/blob/master/src/srcinfo.rs#L85
This parsing would be nice to cover with more tests I think, manual and/or unit.

**Comment by vn971** [comment]
For reference, this is the problematic `PKGBUILD.static` file that is generated:
```
pkgbase+=('ruby-stringex')
pkgdesc='Some [hopefully] useful extensions to Ruby's String class'
pkgver='2.7.1'
pkgrel='1'
url='http://github.com/rsl/stringex'
arch+=('any')
license+=('MIT')
depends+=('ruby')
noextract+=('stringex-2.7.1.gem')
options+=('!emptydirs')
source+=('https://rubygems.org/downloads/stringex-2.7.1.gem')
sha1sums+=('d462d32da69b6d65657d3e3ea436eab0128ea700')
pkgname+=('ruby-stringex')
```

**Comment by vn971** [comment]
And this is the `.SRCINFO`:
```
# Generated by mksrcinfo v8
# Mon Feb 27 01:45:33 UTC 2017
pkgbase = ruby-stringex
	pkgdesc = Some [hopefully] useful extensions to Ruby's String class
	pkgver = 2.7.1
	pkgrel = 1
	url = http://github.com/rsl/stringex
	arch = any
	license = MIT
	depends = ruby
	noextract = stringex-2.7.1.gem
	options = !emptydirs
	source = https://rubygems.org/downloads/stringex-2.7.1.gem
	sha1sums = d462d32da69b6d65657d3e3ea436eab0128ea700

pkgname = ruby-stringex
```

**Comment by vn971** [comment]
Thanks for raising! The underlying issue is that rust-s regexp implicitly add `.*?` at both ends of each pattern -- something I overlooked, unfortunately.
