### ISSUE TITLE
`rua upgrade` sometimes responds with non-AUR packages

### ISSUE THREAD

**Issue by amcooper** [vn971/rua#155]
`rua upgrade` sometimes tells me about non-AUR packages. Today, for example:
```
$ rua upgrade
Package                    Current Latest 
haskell-haddock-library1.9 1.9.0-3 NOT FOUND, ignored 
```
This is a regular (non-AUR) package that was actually installed as a dependency of another regular package.

**Comment by vn971** [comment]
@amcooper this is intended behavior in fact, make the user aware of this no-more-installable package. If you'd design it for yourself, what would be the action you'd like to see? Completely ignore the package? Ask? Error out? List but ignore for actual upgrade?

**Comment by amcooper** [comment]
Completely ignore. I'm expecting rua to concern itself only with packages from the AUR.

Here's the whole flow:
```
$ rua upgrade                     
Package                    Current Latest 
haskell-haddock-library1.9 1.9.0-3 NOT FOUND, ignored 

Do you wish to upgrade them? [O]=ok, [X]=exit. o

And the following AUR packages will need to be built and installed:


Proceed? [O]=ok, Ctrl-C=abort. o

$
```
And then the same again, if I run it again. If rua wants to make me aware of this package's status, I suppose that's fine. If rua _can't_ upgrade this package, it shouldn't offer me that option.

**Comment by vn971** [comment]
@amcooper understood! Seems like an obvious bug actually, understood it now, acknowledging.

Would you want / have time to fix it?

**Comment by amcooper** [comment]
It would be a while before I could get to it, but I'll fix it if no one else has by that time.

**Comment by vn971** [comment]
@amcooper hey, no worries, I'll pick this up, it's a very small change that I know where to do
