### ISSUE TITLE
What does this mean: "NOT FOUND, ignored"?

### ISSUE THREAD

**Issue by refaelsh** [vn971/rua#156]
Hi,

Recently, I've begun getting the following error:
![1_001](https://user-images.githubusercontent.com/2750775/114438464-76965a80-9bd0-11eb-970c-96fa949bbef9.jpg)
Can you guys please explain what does this means?

**Comment by vn971** [comment]
Hi! Are you using the latest RUA? I think I've fixed that in the last version, lemme check..

**Comment by vn971** [comment]
It's another implication of this issue: https://github.com/vn971/rua/issues/155
which got fixed, but no release has been made yet. I'm making one now.

**Comment by refaelsh** [comment]
> Hi! Are you using the latest RUA? I think I've fixed that in the last version, lemme check..

Running `rua --version` gives me `rua 0.17.18`.

**Comment by refaelsh** [comment]
> It's another implication of this issue: #155
> which got fixed, but no release has been made yet. I'm making one now.

Great! Thanks!

**Comment by vn971** [comment]
Overall, in the above screen it's essentially the situation of: "All AUR packages are up-to-date, but there are some packages installed locally that do not exist in neither pacman nor AUR"

**Comment by vn971** [comment]
// BTW, I want to return to the other messages around here (and the PR), but didn't have energy for that yet.. Will do later.

**Comment by refaelsh** [comment]
> // BTW, I want to return to the other messages around here (and the PR), but didn't have energy for that yet.. Will do later.

Thats ok! All is fine! I love you and what you are doing here with Rua. Please, feel free to take your time :-)
Love you man :-)

**Comment by vn971** [comment]
Done, v0.17.19 is out!

**Comment by refaelsh** [comment]
I've upgraded to v0.17.19 and the issue still exists.

**Comment by vn971** [comment]
@refaelsh can you please copy terminal (or screenshot)?

**Comment by refaelsh** [comment]
![1_002](https://user-images.githubusercontent.com/2750775/114602310-22a67700-9c9f-11eb-91f6-87ba070a3ac2.jpg)

**Comment by vn971** [comment]
Yeah, that's how it should be. RUA says that all AUR packages aru up-to-date, but some packages you have locally do not exist in neither pacman nor AUR

**Comment by vn971** [comment]
it no longer asks you to do anything about it though, it just exits successfully, just notifying you about the current state

**Comment by vn971** [comment]
Maybe the text can be made yellow or something as it's not an error, it's just a FYI for the user.

Given this context, what do you think? What would you expect RUA to do when encountering these packages? (I'm not saying I'll incorporate right away, but I'm curious what you think)

**Comment by refaelsh** [comment]
IMHO, and please feel free to ignore me :-), I think that this message should not appear, if those packages are no longer in AUR.

**Comment by refaelsh** [comment]
> it no longer asks you to do anything about it though, it just exits successfully, just notifying you about the current state

Oh! I understand. Then, please feel free to close this issue :-)

**Comment by vn971** [comment]
I've tried to improve the wording here, to make it more explicit and actionable: https://github.com/vn971/rua/commit/3f90120802827a52b1045ef887f8de1697b035d7

**Comment by Moth-Tolias** [comment]
ignoring personal packages as recommended in https://github.com/vn971/rua/commit/3f90120802827a52b1045ef887f8de1697b035d7 results in a second warning:

> rua upgrade
2025-10-29 07:06:31 [WARN] - The following packages have changed in AUR but are ignored in the system: openttd-original-data

however, `openttd-original-data` has _not_ been changed in the aur - it exists only on my machine.
