### ISSUE TITLE
Repeated dependencies installed in incorrect order

### ISSUE THREAD

**Issue by ldr709** [vn971/rua#16]
I ran into this while installing `ruby-gollum`. When a package (in this case `ruby-nokogiri`) is depended upon multiple times and a later depending package is deeper than the first, it will be installed after some of the packages that depend on it and the `makepkg` will fail. This is because packages are installed in order of the depth of the first time the package is required, and instead they need to be in order of the depth of the deepest depending package.

**Comment by vn971** [comment]
Thanks for the report, good catch! I'll take a look.
