### ISSUE TITLE
Rua started having an issue with `libpalm`

### ISSUE THREAD

**Issue by refaelsh** [vn971/rua#166]
Here is what started happening:
```
❯ rua
rua: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory
```
I have no idea what I've done besides running regular `sudo pacman -Syu`.

Help please :-)

**Comment by vn971** [comment]
@refaelsh hey, this unfortunately happened due to pacman upgrade, see this message: https://aur.archlinux.org/packages/rua/#pinned-810636

Since then I re-wrote some parts of rua and now this won't happen again. Yet once you need to upgrade the package manually, as in the comment above

**Comment by refaelsh** [comment]
I am sorry, I must be missing something stupid. I followed the instructions in your link, and here is the result:

```
❯ git clone https://github.com/vn971/rua
Cloning into 'rua'...
remote: Enumerating objects: 2695, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 2695 (delta 70), reused 84 (delta 36), pack-reused 2568
Receiving objects: 100% (2695/2695), 961.70 KiB | 2.00 MiB/s, done.
Resolving deltas: 100% (1875/1875), done.

🏠
❯ cd rua/

…/rua on  master
❯ makepkg si
==> ERROR: PKGBUILD does not exist.

…/rua on  master
❯
```

**Comment by vn971** [comment]
@refaelsh `-si` is with a dash, `makepkg -si`  can you try that?

**Comment by refaelsh** [comment]
Same thing happens:
```
❯ cd rua/

…/rua on  master
❯ makepkg -si
==> ERROR: PKGBUILD does not exist.

…/rua on  master
❯
```

**Comment by vn971** [comment]
@refaelsh oh sorry, the instructions were wrong, it said to clone the Rust repository (github here), not the AUR one. I've updated them now. Correct steps:
```sh
https://aur.archlinux.org/rua.git
makepkg -si
# if you use rustup, then also run:  rustup update
```

**Comment by refaelsh** [comment]
Yeap, that solves it. Thank you.

**Comment by vn971** [comment]
Thanks for the report! There was an actual bug, fixed it thanks to these messages
