### ISSUE TITLE
Pkgbuild still uses the git feature

### ISSUE THREAD

**Issue by Morganamilo** [vn971/rua#170]
the pkgbuild still uses the git feature when pacman-git is installed causing it to fail to build because the feature is now libalpmgit.

Though it should just be removed altogether as the default is to shell out to pacman and that works for all pacman versions.

**Comment by vn971** [comment]
@Morganamilo Thanks for noticing/writing! Fixed it now (pushed a new commit). I've left the pkgrel unchanged because I don't want people to re-build the tool if they have a working version already anyway. Not 100% if that's the right call tho, but leaving it as-is for now
