### ISSUE TITLE
Rua on Arch Arm64?

### ISSUE THREAD

**Issue by Poincare1** [vn971/rua#172]
Following the instructions to build from source(?) gives the following error: 

`git clone https://aur.archlinux.org/rua.git                     20:00:53
Cloning into 'rua'...
remote: Enumerating objects: 502, done.
remote: Counting objects: 100% (502/502), done.
remote: Compressing objects: 100% (319/319), done.
remote: Total 502 (delta 178), reused 502 (delta 178), pack-reused 0
Receiving objects: 100% (502/502), 167.50 KiB | 526.00 KiB/s, done.
Resolving deltas: 100% (178/178), done.
/tmp ❯ cd rua                                                          20:01:20
/tmp/rua master ❯ makepkg -si                                          20:01:21
==> ERROR: rua is not available for the 'aarch64' architecture.
`

**Comment by vn971** [comment]
Hi @Poincare1! The issue is solved now, `rua` should be able to run on Arm64. (Please report if it doesn't!)
