### ISSUE TITLE
Weird failure to build lib32-lzo

### ISSUE THREAD

**Issue by OneMoreByte** [vn971/rua#175]
I ran into an issue with the PKGCONFIG from lib32-lzo. When I try to install with 
```
rua install  lib32-lzo
```
running `./configure` fails with 
```
configure: Configuring LZO 2.10
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc -m32
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/home/user/.cache/rua/build/lib32-lzo/src/lzo-2.10':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
Build failed with exit code 4 in /home/user/.cache/rua/build/lib32-lzo
```

But if I cd into the directory rua creates and run`makepkg` manually, it builds fine. 

Is this user error or is something weird happening in rua?

**Comment by vn971** [comment]
Hey @OneMoreByte, I don't really know, it could be anything from the security limitations that RUA does automatically: https://github.com/vn971/rua#safety

What does `config.log` say (from the text above)?

**Comment by OneMoreByte** [comment]
Sorry for the late response and embarrassed to say I didn't look that over. Looks like it builds and runs a `conftest` and it fails with 
```
./configure: line 3312:   940 Bad system call         (core dumped) ./conftest$ac_cv_exeext
```
which sounds like it's related to the sandbox. Sounds like that's by design. I'll close this.
