### ISSUE TITLE
Static pkgbuild is easy to bypass

### ISSUE THREAD

**Issue by Morganamilo** [vn971/rua#19]
Giving the srcinfo

```
pkgname = foo
pkgver = 1
pkgrel = 1
arch = any
pkgdesc = this';echo hacked;#
```

produces the pkgbuild

```
pkgname+=('foo')
pkgver='1'
pkgrel='1'
arch+=('any')
pkgdesc='this''';echo hacked;#'
```

Which when run through bash or makepkg outputs `hacked`.

Personally I think trying to secure pkgbuilds like this is a bad idea in the first place. Instead I think it's best to just have the user vet the pkgbuild before downloading sources.

**Comment by vn971** [comment]
Damn, it's so sad to see issues like this slipping through. Big thanks for raising the issue!

Apparently I didn't test https://github.com/vn971/rua/blob/master/src/srcinfo.rs#L84
I expected this thing to write `'\''`, but in fact it writes down `'''`.

Long-term, thins thing sounds like a candidate for proper rewrite. I'm not sure which form I want it to take though as the idea was to allow "safe" sources (resources) downloading.. And I didn't want to teach RUA how to do that explicitely.

**Comment by vn971** [comment]
At least one good news for me to avoid total shame: the automatically produced PKGBUILD.static was still run under the jail, just with internet access. Still not good though as something called "--offline" should never be able to reach internet from PKGBUIULD.

**Comment by Morganamilo** [comment]
This seems to work although I am in no way a bash expert, I can't help the feeling that there's some way to break it.

**Comment by vn971** [comment]
@Morganamilo I had the same feeling that there's million of ways to escape stuff and you can't cover it all. Some materials that I could find online though suggests that for `'` the only thing that must be escaped is `'` itself..
I see no other way to support `--offline` builds at the moment. Not sure what to do best here..

**Comment by Morganamilo** [comment]
Why not have the user review the pkgbuild then use makepkg on the proper pkgbuild to download the sources?

**Comment by vn971** [comment]
@Morganamilo that's the default behavior (without `--offline`) already.

**Comment by Morganamilo** [comment]
My point was using makepkg to download the sources then run the rust of the build offline. So just like the existing offline process but use the proper pkgbuild.

**Comment by vn971** [comment]
@Morganamilo Ah, got it!
I'm still thinking about it. There certainly seems to be a use case for the relaxed "--offline" key, when PKGBUILD is executed with online capabilities but a properly written and checked script is assumed. Question is now how to integrate that. Have two "--offline"-like keys?

Maybe you have some ideas on it?

**Comment by Morganamilo** [comment]
Have separate `--offline` and `--static` flags is what comes to mind for me.
