### ISSUE TITLE
Frustrated: confusing behavior when installing xen

### ISSUE THREAD

**Issue by b1f6c1c4** [vn971/rua#28]
I enabled `multilib` from pacman first and ran `rua install xen`
After a very looooooooong wait the compilation is finished.
`rua` asked me
```
Package /home/b1f6c1c4/.cache/rua/xen/build/target/xen-4.11.0-2-x86_64.pkg.tar.xz has no SUID files.
[I]=show install file, [E]=list executable files, [L]=list all files, [T]=run shell to inspect, [O]=ok, proceed.
```
And I typed `i` to view the install file. It looks nice. Afterwards,
```
Package /home/b1f6c1c4/.cache/rua/xen/build/target/xen-4.11.0-2-x86_64.pkg.tar.xz has no SUID files.
[I]=show install file, [E]=list executable files, [L]=list all files, [T]=run shell to inspect, [O]=ok, proceed. o


Package /home/b1f6c1c4/.cache/rua/xen/build/target/xen-docs-4.11.0-2-any.pkg.tar.xz has no SUID files.
[E]=list executable files, [L]=list all files, [T]=run shell to inspect, [O]=ok, proceed. o

Packages need to be installed:

    pacman -U --needed /home/b1f6c1c4/.cache/rua/xen/checked_tars/xen-docs-4.11.0-2-any.pkg.tar.xz

Enter S to `sudo` install it, or install manually and press M when done. s
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) xen-docs-4.11.0-2

Total Installed Size:  3.94 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing xen-docs                          [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Packages need to be installed:

    pacman -U --needed /home/b1f6c1c4/.cache/rua/xen/checked_tars/xen-docs-4.11.0-2-any.pkg.tar.xz

Enter S to `sudo` install it, or install manually and press M when done. s
loading packages...
warning: xen-docs-4.11.0-2 is up to date -- skipping
 there is nothing to do
Packages need to be installed:

    pacman -U --needed /home/b1f6c1c4/.cache/rua/xen/checked_tars/xen-docs-4.11.0-2-any.pkg.tar.xz

Enter S to `sudo` install it, or install manually and press M when done. s
loading packages...
warning: xen-docs-4.11.0-2 is up to date -- skipping
 there is nothing to do
Packages need to be installed:

    pacman -U --needed /home/b1f6c1c4/.cache/rua/xen/checked_tars/xen-docs-4.11.0-2-any.pkg.tar.xz

Enter S to `sudo` install it, or install manually and press M when done. s
loading packages...
warning: xen-docs-4.11.0-2 is up to date -- skipping
 there is nothing to do
Packages need to be installed:

    pacman -U --needed /home/b1f6c1c4/.cache/rua/xen/checked_tars/xen-docs-4.11.0-2-any.pkg.tar.xz

Enter S to `sudo` install it, or install manually and press M when done. m
```
Immediately I tried to `ls /boot` and `ls /etc/xen` to configure xen, but I didn't see the files installed. So I, without thinking about it, typed `rua install xen` and hit enter.
It was not until I saw `makepkg` started downloading `xen-4.11.0.tar.gz` that I realized `rua` deleted `/home/b1f6c1c4/.cache/rua/xen`, INCLUDING targets, WITHOUT noticing me at all.

So two problems:
1. Why `rua` __fails silently__ when installing `xen-4.11.0-2-x86_64.pkg.tar.xz`?
2. Why `rua` delete cache dir __without any notification__ ? Especially when trying to __purge a huge package that failed during installation__ ?

**Comment by vn971** [comment]
Thanks for the report! Sorry for the frustration with the removed artifacts.. Regarding deletion of cache dir -- it's a known thing:

> Smart caching is not implemented yet. To avoid outdated builds, RUA wipes caches in case of possible conflict. This may change in the future.
https://github.com/vn971/rua#limitations

Basically, the program currently has no idea in which state the build directory is, so it always wipes out it entirely. Even with that, however, it makes sense to not touch the "checked_tars" dir while we haven't started a new build yet. I'll do that, that's takeaway N1.

Another thing is that installation went wrong. Guessing by the logs, it only ever proposed to install `xen-docs`, but not `xen` itself. That's takeaway N2.

**Comment by Morganamilo** [comment]
What exactly do you mean by state? You can easily just call `makepkg -C`. For the checked tars I'm not so sure how you'd want to handle that.

**Comment by vn971** [comment]
@Morganamilo I mean understanding whether a package lase already being built, if that was the latest version, etc. Basically, if RUA sees a directory, it currently has no way to know whether it's the last version that we need to build, and deletes it to ensure that build is not outdated.

**Comment by vn971** [comment]
Even though frustrating, the bug doesn't strike me as critical BTW, as it is: 1. documented 2. doesn't lead to stuff being run outside of jail, wrong package being installed on system, etc. Needless to say I will work on it anyways.

**Comment by Morganamilo** [comment]
But makepkg will automatically rebuild the package if it is out of date.

**Comment by vn971** [comment]
@Morganamilo but how to update the AUR repo and its PKGBUILD?

**Comment by Morganamilo** [comment]
Git pull?

**Comment by vn971** [comment]
@Morganamilo so instead of cleaning each time, you propose to build in a dirty dir... I have to think about it. It's not the way I planned it, but maybe it's OK.

**Comment by Morganamilo** [comment]
Well you need to reset first to get rid of changes such as automated pkgver bumps. But you get to keep the sources and built packages that way.

**Comment by vn971** [comment]
I fixed the `sudo` loop as well now, when it asked the same question over again even though the package is already installed. Commit https://github.com/vn971/rua/commit/dffee34c789827465c922f1b8245862ef8da32d7

**Comment by vn971** [comment]
And fixed the last part of the issue now -- missing to install `xen` and only installing `xen-docs` with the latest commit. Fixed in the latest commit & the new release.

The story with split packages should still be improved, but at least some common patterns are now covered. Hopefully I'll have some time for completely finishing split packages story in the weekends, but no promises.
