### ISSUE TITLE
implement Update functionality

### ISSUE THREAD

**Issue by nolik** [vn971/rua#34]
Hi, all. As a comma Arch user i wanna have update functionality of all available for update packages.
(something like yay main command).
I able to try implement it, and it will be grate to hear you advice about way to implement it.

**Comment by nolik** [comment]
Suppose plan should be smth like this:

1.  synchronizes the repository databases 
2.  find list out-of-date packages
3.  download list out-of-date packages
4.  update packages one-by-one in jail

It's too simplify and each step need to detalize.

**Comment by Morganamilo** [comment]
In simple terms:
 - iterate through all packages with `alpm_get_localdb` and `alpm_db_get_pkgcache`
 - filter the list to packages that exist in the AUR and are newer than local, using `raur::info` and `alpm_pkg_vercmp`
- then use that list to install the packages as if they were specified on the command line.

**Comment by vn971** [comment]
@Morganamilo precisely!
Only thing to add -- we can probably also TRY to take care of "-git" / "-hg" / "-svn" packages somehow.

This area has loads of unanswered questions, however. How to do that? One alternative is to propose updating those if they haven't been updated in the last N days. But how would you know if a package is "-git"-like? Only by the name? Or would you store this information into config somehow? But then again RUA doesn't have package-level configs yet -- how would we implement those?

One proposal I had in mind is to start by looking at names of the packages (some regexp), and work from there analyzing the needs of real users.

**Comment by Morganamilo** [comment]
Yay caches the packages with git sources and uses `git ls-remote` to look for new commits directly. Pros is it just works instantly and knows when there is a new commit. cons is it needs to cache the data and only works for git.

Also regex is overkill, just check the suffix.
