### ISSUE TITLE
multilib dependencies cause an error

### ISSUE THREAD

**Issue by theel0ja** [vn971/rua#4]
Package I tried: https://aur.archlinux.org/packages/foobar2000/

It has Wine (arch repos, i think) as a dependency.

```
[eliaso@home ~]$ rua install foobar2000
foobar2000 depends on AUR package wine. Trying to fetch it...
thread 'main' panicked at 'Repository wine does not have an SRCINFO file. Does this package exist in AUR?', src/aur.rs:38:2
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>
```

**Comment by vn971** [comment]
This one is because `wine` is really not an AUR package, but rather a package that exists in [multilib] repository of official pacman. See here: https://wiki.archlinux.org/index.php/Wine#Installation  for wine installation on ArchLinux.

**Comment by vn971** [comment]
@theel0ja note that RUA has no right to change values in your `/etc/pacman.conf`, nor should it have. It's your choice to enable multilib or not.
