### ISSUE TITLE
respect pacman HoldPkg packages when doing upgrade

### ISSUE THREAD

**Issue by vn971** [vn971/rua#57]
Currently, RUA tries to offer upgrades for any AUR packages that have upstream updates. We also have pacman-s `HoldPkg`, which serves a different, but similar purpose (its main purpose is to instruct pacman on its actions). Re-using it in RUA seems like a straightforward action.

Opinions welcomed. 

Possible implementation 1: this list of ignored packages can be obtained by `pacconf --null HoldPkg`. It will require `pacconf` in (optional?) dependencies though.

Possible implementation 2: this list can be obtained by using `pacman-conf HoldPkg`. This utility is part of `pacman` package, and thus is always present on the target system. It does not support the "null terminated" splitting, but we don't need that because pacman.conf is newline-split anyway.

**Comment by Morganamilo** [comment]
Why not just use ignorepkg?

**Comment by vn971** [comment]
Could be used as well I guess. But pacman-conf seems to be working as well, and it's not performance-critical (in fact, barely measurable, if at all).
Would also require about the same amount of code that the current solution took.

**Comment by vn971** [comment]
That's how I feel about the situation now, anyway. When I wrote this feature, I just asked on #archlinux-aur on possible solutions, and picked the first one that seemed working.

**Comment by Morganamilo** [comment]
Not sure what you mean. You'd still be using pacman-conf, just `pacman-conf IgnorePkg` insead.

**Comment by vn971** [comment]
@Morganamilo did just that in commit above.
