### ISSUE TITLE
rua fails to build

### ISSUE THREAD

**Issue by fox8091** [vn971/rua#61]
rua currently fails to build, failing on this line https://github.com/vn971/rua/blob/master/src/pacman.rs#L63.
The error message is
> the trait `std::convert::From<&std::string::String>` is not implemented for `std::string::String`

**Comment by vn971** [comment]
Interesting.. It certainly builds for me, just checked. The CI is happy with the build status as well, says "build | passing" https://github.com/vn971/rua https://travis-ci.org/vn971/rua/builds

Which version of Rust do you use?

Maybe I can make some changes to support a bit older versions of Rust. Meanwhile, if you use rustup and you'd want to upgrade the rust version, use `rustup update`

**Comment by vn971** [comment]
You can get the version of Rust that you're using by runnig `rustc --version`.

**Comment by fox8091** [comment]
It was an outdated version of Rust, but I'm not sure how to figure out the version I was on. rua does build on the latest stable version though.

**Comment by vn971** [comment]
@fox8091 did you build via AUR (`makepkg -i` or another helper), or you've built it the Rust way, `cargo install rua` ?
That could help understanding what's happening.

**Comment by vn971** [comment]
The problem most probably only affects older versions of Rust. (Again, all manual tests and CI run just fine).
So, closing. Please re-open if the version will be known and it'll be more or less recent. Otherwise, run `rustup update`.
