### ISSUE TITLE
Anything that requires AUR dependencies to build now fails.

### ISSUE THREAD

**Issue by Morganamilo** [vn971/rua#67]
The reasoning behind commit https://github.com/vn971/rua/commit/1925fc244861859da8304a9a96d2507c5a26fc66 really confuses me. Skipping dependency checks is a bad idea. If the issue is that makepkg is complaining about missing deps... then your problem is you need to have the deps installed, not just skip dependency checks.

As a result, anything that requires an AUR package to build now fails under rua.

**Comment by vn971** [comment]
I was again trapped by the naming in the PKGBUILD that I find extremely counter-intuitive. You could think that `makedepends` relates to things required at make time, `depends` relates to things required at run time, and specifying a package in both `depends` and `makedepends` would require both.

In reality, however, `depends` silently implies `makedepends`. I forgot about that implication. Acknowledging the issue, will fix.

**Comment by Morganamilo** [comment]
I did mention that in #63, maybe you missed it?

**Comment by vn971** [comment]
I'm very tired recently (lots of things going on) and I didn't have energy to fully address #63, but I wanted to make a quick fix for one of the issues mentioned there (but I though you were wrong on grouping notice and wanted to make a quicker fix).

I did fix both this issue and the original now though. Even though I'm a bit scared on releasing now, considering 2 AM and being tired. Will release as a tag tomorrow.

**Comment by vn971** [comment]
.. And this: https://github.com/vn971/rua/commit/dea2eb100129d4251605a32db6cef1da0d42102c
