### ISSUE TITLE
code: deduplicate print_package_info::info and aur_rpc_utils::info_map

### ISSUE THREAD

**Issue by vn971** [vn971/rua#73]
See subject.

**Comment by aacunningham** [comment]
I'm willing to take this on if you want. I can probably get an implementation of this where `info_map` is called inside of `info` if that sounds good to you.

**Comment by vn971** [comment]
@aacunningham sorry for the late reply.
Sure! It would be quite welcomed.

**Comment by CPerezz** [comment]
Shoudn't this be closed since #88 was merged?

**Comment by vn971** [comment]
@CPerezz thanks! I think you're right indeed. I'll answer the other comments on other PR-s a bit later.
