### ISSUE TITLE
Configuration for alternative sudo command

### ISSUE THREAD

**Issue by kuon** [vn971/rua#79]
On my system, I use `doas`, for different reasons. I would love for rua to support configuration of the `sudo` command for something else.

**Comment by vn971** [comment]
@kuon you probably don't want to `ln -s /usr/bin/doas /usr/local/bin/sudo`, right? Doas is not exactly a drop-in replacement?

**Comment by kuon** [comment]
No it is not, but more importantly, my doas isn't installed as `doas` but as a custom name, like `dx8`, in a non standard location, this is a trade off I found that let me type short commands while protecting against malicious scripts. Of course it's not perfect, and won't help against a targeted attack, but it works against most "woopsises".

**Comment by vn971** [comment]
@kuon: what do you think of a PR like this: https://github.com/vn971/rua/pull/80

Does that sound like something convenient to use for you?

TBH I'm thinking of delete CLI support and only rely on environment variables. After all, I have hard time imagining people switch "sudo"-like commands often between invocations.

**Comment by kuon** [comment]
I think ENV or conf file would make more sense than a command line flag. ENV is easier and I don't think if a config file would be justified.

**Comment by vn971** [comment]
yeah, so we're on the same line of thought here. Updated the PR, will soon merge.

**Comment by vn971** [comment]
This was implemented in PR-80, closing.
