### ISSUE TITLE
implement zstd archive format

### ISSUE THREAD

**Issue by vn971** [vn971/rua#82]
ArchLinux recently announced that they will use/support zstd archive format: https://www.archlinux.org/news/required-update-to-recent-libarchive/

Support for it in RUA is not urgent/critical (it will just build in archives it knows), but is ultimately desired to move along with upstream development. Especially the `tarcheck` command, which should be able to look into packages built with e.g. just `makepkg`.

Rust has some support via:
* rust library with bindings to OS library: https://github.com/gyscos/zstd-rs
* pure rust library: https://github.com/KillingSpark/zstd-rs

**Comment by Morganamilo** [comment]
Arch's repos are switching from `xz` to `zstd`. makepkg's default will still be `gzip`.

**Comment by Morganamilo** [comment]
Actually I partially take that back. makepkg's default is `gzip` but the makepkg in arch's repos is tweaked to use `xz` by default. That would make me assume the default will indeed be `zstd`.

**Comment by vn971** [comment]
// I've raised a feature request to support streaming read in zstd-rs: https://github.com/KillingSpark/zstd-rs/issues/4

**Comment by vn971** [comment]
Closed with https://github.com/vn971/rua/pull/94
