### ISSUE TITLE
feature request: option for upgade to only output

### ISSUE THREAD

**Issue by AblingerOscar** [vn971/rua#86]
It would be nice, if there was an option for `rua upgrade` that would not prompt to update the packages, but instead only list them.

This would be useful, if you only want to check if there are outdated packages (for instance in a script to regularily check the amount of outdated packages and print them somewhere (e.g. polybar))

**Comment by vn971** [comment]
Sounds like a straightforward and natural feature/property. Would you want to implement it, or would you prefer for me (or somebody else) to implement it? Both are pretty fine.

**Comment by vn971** [comment]
The way to do it, I guess, would be a CLI flag like `--printonly`, e.g. `rua update --printonly`. Didn't think much about the name yet, maybe will end up with something different.

**Comment by AblingerOscar** [comment]
It seems pretty straight-forward. I'd offer to make a PR, but I've never worked with Rust before, so it'd probably if my first contact with it is not in a live project, even if it's just a small change :P

I imagined a CLI flag, yes. `--printonly` sounds good.
Alternatively, I initially thought about `-l --list`, but yours is a bit more descriptive

**Comment by vn971** [comment]
No problem, I'll make the change then. If this flag is intended to be used from scripts, then the additional length shouldn't hurt too much, so I'll start with `--printonly`.
