### ISSUE TITLE
depends_arch should not assume pacman architecture == uname

### ISSUE THREAD

**Issue by Morganamilo** [vn971/rua#9]
For architecture specific fields (e.g. depends_x86_64) the architecture should correspond to the architecture defined in pacman.conf, not the system architecture.

On x84_64 this doesn't really matter as pacman.conf and uname happen to agree.

But on other architectures like arm, `uname -m` gives `armv7l` while pacman.conf contains `Architecture = armv7h`.

**Comment by vn971** [comment]
Remark to anyone fixing this bug (probably me).
The correct way to get architecture is to invoke `pacman-conf Architecture`, or to use libalpm.

**Comment by vn971** [comment]
Fixed in https://github.com/vn971/rua/commit/c76710a83a916931e44c64375a53eabe2b6ad396  and  https://github.com/vn971/rua/commit/fc548e3f26f006799333675c9ef1ee7358272f26
