### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [vn971/rua#93]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by vn971** [comment]
Am I right that the request is to support `.pkg.tar.gz` archive format?

**Comment by vn971** [comment]
Notice for myself: if `gzip` support is at question, this library might be worth looking into. Need to see if it can be wrapped as streaming tho.

**Comment by es20490446e** [comment]
I just read that Arch is planning to default to zstd, so no fix will be needed here.

- [Arch thread](https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029520.html)
- [Pacman git log](https://git.archlinux.org/svntogit/packages.git/log/?h=packages/pacman)

**Comment by vn971** [comment]
@es20490446e I got interested by all that and implemented .gz archives anyway though:) https://github.com/vn971/rua/commit/fb897550469c03558d0f1ada7d1b7e242098b59a

Also, raised a feature request here: https://github.com/KillingSpark/zstd-rs/issues/4

**Comment by vn971** [comment]
And yeah, there's an issue to support zstd here as well (created by me few weeks ago).

**Comment by es20490446e** [comment]
Oh, okay :)
